# Generated by Django 5.0.7 on 2024-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_text',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
